<#--
	Introduction:
		Reset password page
		
	Url:
		/membership/reset-password.*
		
	Controller:
		com.beelun.shoppro.web.MembershipController.handleRestPasswordRequest(HttpServletRequest, HttpServletResponse)
		
	Model:
		Type	Name	Description
		---------------------------------
		String	token	the token generated by controller
-->

<#import "/spring.ftl" as spring/> 
<#assign xhtmlCompliant = true in spring>
<head>
  <title><@spring.message "resetpassword.title"/></title>
</head>
<#if resetSuccess?exists> <#if resetSuccess=true>
<div class="round graypanel narrow">
  <span class="gheader">
    <img src="${rc.getContextPath()}/images/ok.png" class="headimg">
    Done </span>
  <div class="round whitepanel">
    <p>
      Password reset is completed successfully. please <a href="/membership/login.html"
        title="login">login</a> with your new password.</p>
  </div>
</div>
<#else>
<div class="round graypanel narrow">
  <span class="gheader">
    <img src="${rc.getContextPath()}/images/error.png" class="headimg">
    error </span>
  <div class="round whitepanel">
    <p>
      Fail to reset. Please retry.</p>
  </div>
</div>
</#if> <#else>
<div class="round graypanel narrow">
  <span class="gheader">
    <img src="${rc.getContextPath()}/images/signin.png" class="headimg">
    <@spring.message "resetpassword.title"/> </span>
  <div class="round whitepanel">
    <form method="post" action="<@spring.url '/membership/reset-password.html'/>" id="passwordForm"
    name="passwordForm">
    <#if token?exists>
    <input type="hidden" id="token" name="token" value="${token}" />
    </#if>
    <table class="singletr">
      <tr>
        <th>
          <label for="password">
            <@spring.message "user.newPassword"/>:</label>
        </th>
        <td>
          <input name="password_name" type="password" id="password" />
        </td>
      </tr>
      <tr>
        <th>
          <label for="repassword">
            <@spring.message "user.repassword"/>:</label>
        </th>
        <td>
          <input name="repassword_name" type="password" id="repassword" />
        </td>
      </tr>
      <tr>
        <td>
        </td>
        <td>
          <div id='passwordForm_errorloc' class='error_strings' style="color: red">
          </div>
        </td>
      </tr>
      <tr>
        <td>
        </td>
        <td>
          <input type="submit" class="button" name="save" value="Reset password" />
        </td>
    </table>
    </form>
  </div>
</div>

<script type="text/javascript">
  var frmvalidator = new Validator("passwordForm");
  frmvalidator.EnableOnPageErrorDisplaySingleBox();
  frmvalidator.EnableMsgsTogether();
  frmvalidator.EnableFocusOnError(true);
  frmvalidator.addValidation("password", "req");
  frmvalidator.addValidation("repassword", "req");

  function DoCustomValidation() {
    var frm = document.forms["passwordForm"];
    if (frm.password.value != frm.repassword.value) {
      sfm_show_error_msg('The Password and verified password don not match!', frm.password);
      return false;
    }
    else {
      return true;
    }
  }

  frmvalidator.setAddnlValidationFunction("DoCustomValidation");
</script>

</#if>