//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyDog.SL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HappyDog.SL.Resources.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误的用户名或密码。.
        /// </summary>
        public static string AUTH_NOROLE {
            get {
                return ResourceManager.GetString("AUTH_NOROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; 返回.
        /// </summary>
        public static string BUTTON_DV_BACK {
            get {
                return ResourceManager.GetString("BUTTON_DV_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string BUTTON_DV_EDIT {
            get {
                return ResourceManager.GetString("BUTTON_DV_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一个.
        /// </summary>
        public static string BUTTON_DV_NEXT {
            get {
                return ResourceManager.GetString("BUTTON_DV_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前一个.
        /// </summary>
        public static string BUTTON_DV_PREVIOUS {
            get {
                return ResourceManager.GetString("BUTTON_DV_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string BUTTON_DV_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_DV_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string DV_FALSE {
            get {
                return ResourceManager.GetString("DV_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未分组.
        /// </summary>
        public static string DV_NOGROUP {
            get {
                return ResourceManager.GetString("DV_NOGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无.
        /// </summary>
        public static string DV_NULL {
            get {
                return ResourceManager.GetString("DV_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string DV_TRUE {
            get {
                return ResourceManager.GetString("DV_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法解析Url或XML数据。.
        /// </summary>
        public static string ERROR_400_BadRequest {
            get {
                return ResourceManager.GetString("ERROR_400_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工号或密码错误。.
        /// </summary>
        public static string ERROR_401_Unauthorized {
            get {
                return ResourceManager.GetString("ERROR_401_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到指定的资源。.
        /// </summary>
        public static string ERROR_404_NotFound {
            get {
                return ResourceManager.GetString("ERROR_404_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交的数据已过时或不合法。.
        /// </summary>
        public static string ERROR_409_Conflict {
            get {
                return ResourceManager.GetString("ERROR_409_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发生无法恢复的内部程序错误。.
        /// </summary>
        public static string ERROR_500_IntertalServerError {
            get {
                return ResourceManager.GetString("ERROR_500_IntertalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该项的格式没有定义。请联系管理员。.
        /// </summary>
        public static string ERROR_EMPTY_RULE_HINT {
            get {
                return ResourceManager.GetString("ERROR_EMPTY_RULE_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string HEADER_LOGOFF {
            get {
                return ResourceManager.GetString("HEADER_LOGOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string LOGIN_BUTTON {
            get {
                return ResourceManager.GetString("LOGIN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string LOGIN_PSWD {
            get {
                return ResourceManager.GetString("LOGIN_PSWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理员邮件.
        /// </summary>
        public static string LOGIN_USERID {
            get {
                return ResourceManager.GetString("LOGIN_USERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (共{1}条记录).
        /// </summary>
        public static string MAINVIEW_RECORDSNUMBER {
            get {
                return ResourceManager.GetString("MAINVIEW_RECORDSNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - 完成。.
        /// </summary>
        public static string MSG_TASKDONE {
            get {
                return ResourceManager.GetString("MSG_TASKDONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} - 错误。.
        /// </summary>
        public static string MSG_TASKERROR {
            get {
                return ResourceManager.GetString("MSG_TASKERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该视图没有数据。.
        /// </summary>
        public static string NO_DATA {
            get {
                return ResourceManager.GetString("NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分组.
        /// </summary>
        public static string SEARCHBAR_GROUPINGBUTTON {
            get {
                return ResourceManager.GetString("SEARCHBAR_GROUPINGBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索.
        /// </summary>
        public static string SEARCHBAR_SEARCHBUTTON {
            get {
                return ResourceManager.GetString("SEARCHBAR_SEARCHBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欲搜索....
        /// </summary>
        public static string SEARCHBAR_SEARCHFOR {
            get {
                return ResourceManager.GetString("SEARCHBAR_SEARCHFOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoppro管理平台 (Beta).
        /// </summary>
        public static string SYSTEM_NAME {
            get {
                return ResourceManager.GetString("SYSTEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成系统实体对象....
        /// </summary>
        public static string TASKDSP_ENTITYBUILDER {
            get {
                return ResourceManager.GetString("TASKDSP_ENTITYBUILDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在生成系统实体对象集合....
        /// </summary>
        public static string TASKDSP_ENTITYSETBUILDER {
            get {
                return ResourceManager.GetString("TASKDSP_ENTITYSETBUILDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 准备用户及用户权限....
        /// </summary>
        public static string TASKDSP_LOGIN {
            get {
                return ResourceManager.GetString("TASKDSP_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建立数据摘要....
        /// </summary>
        public static string TASKDSP_SCHEMABUILDER {
            get {
                return ResourceManager.GetString("TASKDSP_SCHEMABUILDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载当前用户的视图和目录树....
        /// </summary>
        public static string TASKDSP_TREEVIEWBUILDER {
            get {
                return ResourceManager.GetString("TASKDSP_TREEVIEWBUILDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string TOOLBAR_DELETE {
            get {
                return ResourceManager.GetString("TOOLBAR_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出商品.
        /// </summary>
        public static string TOOLBAR_EXPORT {
            get {
                return ResourceManager.GetString("TOOLBAR_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入商品.
        /// </summary>
        public static string TOOLBAR_IMPORT {
            get {
                return ResourceManager.GetString("TOOLBAR_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更多操作.
        /// </summary>
        public static string TOOLBAR_MORE {
            get {
                return ResourceManager.GetString("TOOLBAR_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        public static string TOOLBAR_NEW {
            get {
                return ResourceManager.GetString("TOOLBAR_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string TOOLBAR_REFRESH {
            get {
                return ResourceManager.GetString("TOOLBAR_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入数据中....
        /// </summary>
        public static string WAITINDICATOR_LOADING {
            get {
                return ResourceManager.GetString("WAITINDICATOR_LOADING", resourceCulture);
            }
        }
    }
}
